'''
Abstracts logic for mapping countries by name to their WHO regional categories

- African Region (AFR)
- Region of the Americas (AMR)
- South-East Asian Region (SEAR)
- European Region (EUR)
- Eastern Mediterranean Region (EMR)
- Western Pacific Region (WPR)

reference: https://en.wikipedia.org/wiki/List_of_WHO_regions
'''
WHO_1 = {
    'afro': [
        'Algeria',
        'Angola',
        'Cabo Verde',
        'Congo',
        'DRC',
        'Eswatini',
        'Sao Tome and Principe',
        'Benin',
        'South Sudan',
        'Western Sahara',
        'Congo (Brazzaville)',
        'Congo (Kinshasa)',
        'Cote d\'Ivoire',
        'Botswana',
        'Burkina Faso',
        'Burundi',
        'Cameroon',
        'Cape Verde',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Ivory Coast',
        'Democratic Republic of the Congo',
        'Equatorial Guinea',
        'Eritrea',
        'Ethiopia',
        'Gabon',
        'Gambia',
        'Ghana',
        'Guinea',
        'Guinea-Bissau',
        'Kenya',
        'Lesotho',
        'Liberia',
        'Madagascar',
        'Malawi',
        'Mali',
        'Mauritania',
        'Mauritius',
        'Mozambique',
        'Namibia',
        'Niger',
        'Nigeria',
        'Republic of the Congo',
        'Rwanda',
        'São Tomé and Príncipe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'Somalia',
        'South Africa',
        'Swaziland',
        'Togo',
        'Uganda',
        'Tanzania',
        'Zambia',
        'Zimbabwe',
    ],
    'paho': [
        'Antigua and Barbuda',
        'Argentina',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Bolivia',
        'Brazil',
        'Canada',
        'Chile',
        'Colombia',
        'Costa Rica',
        'Cuba',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'El Salvador',
        'Grenada',
        'Guatemala',
        'Guyana',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Mexico',
        'Nicaragua',
        'Panama',
        'Paraguay',
        'Peru',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'United States',
        'US',
        'USA',
        'Uruguay',
        'Venezuela',
    ],
    'searo': [
        'Bangladesh',
        'Bhutan',
        'North Korea',
        'India',
        'Indonesia',
        'Maldives',
        'Myanmar',
        'Burma',
        'Nepal',
        'Sri Lanka',
        'Thailand',
        'Timor-Leste',
    ],
    'euro': [
        'Albania',
        'Andorra',
        'Greenland',
        'Kosovo',
        'Holy See',
        'Vatican City',
        'Liechtenstein',
        'Armenia',
        'Czechia',
        'Austria',
        'Azerbaijan',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Georgia',
        'Germany',
        'Greece',
        'Hungary',
        'Iceland',
        'Ireland',
        'Israel',
        'Italy',
        'Kazakhstan',
        'Kyrgyzstan',
        'Latvia',
        'Lithuania',
        'Luxembourg',
        'Malta',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'North Macedonia',
        'Norway',
        'Poland',
        'Portugal',
        'Moldova',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Tajikistan',
        'Turkey',
        'Turkmenistan',
        'Ukraine',
        'United Kingdom',
        'UK',
        'Uzbekistan',
    ],
    'emro': [
        'Afghanistan',
        'Bahrain',
        'Djibouti',
        'Egypt',
        'Iran',
        'Iraq',
        'Jordan',
        'Kuwait',
        'Lebanon',
        'Libya',
        'Morocco',
        'Oman',
        'Pakistan',
        'Palestine',
        'West Bank and Gaza',
        'Qatar',
        'Saudi Arabia',
        'Somalia',
        'Sudan',
        'Syria',
        'Tunisia',
        'United Arab Emirates',
        'UAE',
        'Yemen',
    ],
    'wpro': [
        'Australia',
        'Brunei',
        'Cambodia',
        'China',
        'Cook Islands',
        'Fiji',
        'Japan',
        'Kiribati',
        'Laos',
        'Malaysia',
        'Marshall Islands',
        'Micronesia',
        'Mongolia',
        'Nauru',
        'New Zealand',
        'Niue',
        'Palau',
        'Papua New Guinea',
        'Philippines',
        'South Korea',
        'Samoa',
        'Singapore',
        'Solomon Islands',
        'Taiwan',
        'Taiwan*',
        'Tonga',
        'Tuvalu',
        'Vanuatu',
        'Vietnam',
    ],
}
WHO_2 = {
    'afro': [
        'Algeria',
        'Angola',
        'Cabo Verde',
        'Eswatini',
        'Sao Tome and Principe',
        'Benin',
        'South Sudan',
        'Western Sahara',
        'Congo (Brazzaville)',
        'Congo (Kinshasa)',
        'Cote d\'Ivoire',
        'Botswana',
        'Burkina Faso',
        'Burundi',
        'Cameroon',
        'Cape Verde',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Ivory Coast',
        'Democratic Republic of the Congo',
        'Equatorial Guinea',
        'Eritrea',
        'Ethiopia',
        'Gabon',
        'Gambia',
        'Ghana',
        'Guinea',
        'Guinea-Bissau',
        'Kenya',
        'Lesotho',
        'Liberia',
        'Madagascar',
        'Malawi',
        'Mali',
        'Mauritania',
        'Mauritius',
        'Mozambique',
        'Namibia',
        'Niger',
        'Nigeria',
        'Republic of the Congo',
        'Rwanda',
        'São Tomé and Príncipe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'Somalia',
        'South Africa',
        'Swaziland',
        'Togo',
        'Uganda',
        'Tanzania',
        'Zambia',
        'Zimbabwe',
    ],
    'paho': [
        'Antigua and Barbuda',
        'Argentina',
        'Bahamas',
        'Barbados',
        'Belize',
        #'Bermuda',
        'Bolivia',
        'Brazil',
        'Canada',
        'Chile',
        'Colombia',
        'Costa Rica',
        'Cuba',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'El Salvador',
        'Grenada',
        'Guatemala',
        'Guyana',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Mexico',
        'Nicaragua',
        'Panama',
        'Paraguay',
        'Peru',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'United States',
        'US',
        'USA',
        'Uruguay',
        'Venezuela',
    ],
    'searo': [
        'Bangladesh',
        'Bhutan',
        'North Korea',
        'India',
        'Indonesia',
        'Maldives',
        'Myanmar',
        'Burma',
        'Nepal',
        'Sri Lanka',
        'Thailand',
        'Timor-Leste',
    ],
    'euro': [
        'Albania',
        'Andorra',
        'Greenland',
        'Kosovo',
        'Holy See',
        'Liechtenstein',
        'Armenia',
        'Czechia',
        'Austria',
        'Azerbaijan',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Georgia',
        'Germany',
        'Greece',
        'Hungary',
        'Iceland',
        'Ireland',
        'Israel',
        'Italy',
        'Kazakhstan',
        'Kyrgyzstan',
        'Latvia',
        'Lithuania',
        'Luxembourg',
        'Malta',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'North Macedonia',
        'Norway',
        'Poland',
        'Portugal',
        'Moldova',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Tajikistan',
        'Turkey',
        'Turkmenistan',
        'Ukraine',
        'United Kingdom',
        'Uzbekistan',
    ],
    'emro': [
        'Afghanistan',
        'Bahrain',
        'Djibouti',
        'Egypt',
        'Iran',
        'Iraq',
        'Jordan',
        'Kuwait',
        'Lebanon',
        'Libya',
        'Morocco',
        'Oman',
        'Pakistan',
        'Palestine',
        'West Bank and Gaza',
        'Qatar',
        'Saudi Arabia',
        'Somalia',
        'Sudan',
        'Syria',
        'Tunisia',
        'United Arab Emirates',
        'Yemen',
    ],
    'wpro': [
        'Australia',
        'Brunei',
        'Cambodia',
        'China',
        'Cook Islands',
        'Fiji',
        'Japan',
        'Kiribati',
        'Laos',
        'Malaysia',
        'Marshall Islands',
        'Micronesia',
        'Mongolia',
        'Nauru',
        'New Zealand',
        'Niue',
        'Palau',
        'Papua New Guinea',
        'Philippines',
        'South Korea',
        'Samoa',
        'Singapore',
        'Solomon Islands',
        'Taiwan',
        'Taiwan*',
        'Tonga',
        'Tuvalu',
        'Vanuatu',
        'Vietnam',
    ]
}

WHO_ALIAS = {
    'afro': 'Africa',
    'paho': 'Americas',
    'searo': 'South-East Asia',
    'emro': 'Eastern Mediterranean',
    'wpro': 'Western Pacific',
    'euro': 'Europe'
}


def who(variation: bool = False) -> dict():
    """
    Placeholder
    """
    if variation is True:
        return WHO_2

    return WHO_1


def whomap(variation: bool = False) -> dict():
    """
    Placeholder
    """
    return_val = dict()
    data = who(variation=variation)
    data_keys = who(variation=variation).keys()
    for k in data_keys:
        data_key = k
        data_val = data[data_key]
        for locality in data_val:
            print(f"{k}: {locality}")
            return_val[locality] = WHO_ALIAS[k]
    return return_val

def whomembers(variation: bool = False, sel = None, keys_only = False) -> dict():
    """
    Placeholder
    """
    data = who(variation=variation)
    return_val = dict()
    for data_key, data_val in data.items():
        alias = WHO_ALIAS[data_key]
        for country in data_val:
            if sel is not None:
                if sel == alias:
                    return_val[country] = alias
            else:
                return_val[country] = alias
    if keys_only is not False:
        return_val = list(
            return_val.keys()
        )
    return return_val
